
전통적으로 자원이 제대로 닫힘을 보장하는 수단으로 try-finally가 쓰였다. 
예외가 발생하거나 메서드에서 반환되는 경우를 포함해서 말이다. 

```java 
static String firstLineOfFile(String path) throws IOException {
	BufferedReader br = new BufferedReader(new FileReader(path));
	try{
		return br.readLine();
	} finally {
		bre.close();
	}
}
```

```java
static void copy(String src, String dst) throw IOException{
	InputStream in = new FileInputStream(src);
	try{
		OutPutStream out = new FileOutputStream(dst);
		try{
				byte[] buf  new byte[BUFFER_SIZE];
				int n;
				while((n = in.read(buf)) >= 0)
					out.write(buf,0,n);
			}finally{
				out.close();
			}
	}
}
```

하지만, try-with-resource를 사용하도록 하자 

```java
static String firstLineOfFile(String path) throws IOException{
	try(BufferedReader br = new BufferedReader(new FileReader(path))){
		return br.readLine();
	}
}
```

```java
static void copy(String src, String dst) throws IOException {
	try(InputStream in = new FileInputStream(src);
	    OutputStream out = new FileOutputStream(dst)) {
	    byte[] buf = new byte[BUFFER_SIZE];
	    int n;
	    while((n = in.read(buf) >= 0))
		    out.wirte(buf,0,n);
	    }
}
```

catch를 같이 사용할 경우는 하기와 같이 

```java
static String firstLineOfFile(String path) throws IOException{
	try(BufferedReader br = new BufferedReader(new FileReader(path))){
		return br.readLine();
	} catch(IOException e){
		return defaultVal;
	}
}
```